# Generated by Django 4.0.4 on 2022-06-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_article_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterReceipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
